#!/usr/bin/env mea-pl

from mea_pipeline import cout, cerr, cexit, arg_parser


def init_argparser():
    p = arg_parser(
        "Gather candidate regions for signals generated by tab-annotate-signals"
    )

    p.add_argument("-o", "--outfile", default=None)
    p.add_argument("--annotation-file", default=None, help="GFF-based annotation file")
    p.add_argument("infiles", nargs="+")

    return p


def tab_summarize_signals(args):

    pass


def main(args):
    tab_summarize_signals(args)


# EOF
